### PR TITLE
Team 2 some new features and overall code reformat fixing most intelliJ warnings/issues (may cause merge conflicts is not merged early)

### PR DESCRIPTION
**Pull request by eco9898**
As this edits a lot of files at once and reworks some base functionality I hope it can be merged in early to prevent major merge conflicts later
This includes some early new features from team2 as well as:
- fixing the majority of issues found by intelliJ
- fixing issues found by IntelliJ code inspector
- removing trailing white spaces
- syncing style via built-in intelliJ tool

### CODE REVIEW

**Comment by eco9898** [comment]
I recommend hiding whitespace changes as most changes are white space/indentations

**Comment by Jonoym** [comment]
Changes look good, I'm getting the same issue as last time when trying to run the game through gradle but should be a similar fix to last time as well. 

Side note: How are we going to go about damage balancing? At the moment we keep increasing hp then increasing damage.

**Comment by eco9898** [comment]
> How are we going to go about damage balancing?

I increased the damage because roguelike games generally punish the player a lot for being hit. and the fast arrows and tracking arrows are meant to be rarer attacks the do cause a lot of damage if they aren't avoided properly

**Comment by eco9898** [comment]
> I'm getting the same issue as last time when trying to run the game through gradle

Sorry, there are some members in my group that need to enable some settings to build the project which other computers can't handle. This is something that should needs to be modified personally a lot... 
If you revert the changes listed at this commit it should run fine: https://github.com/UQdeco2800/2021-studio-2/commit/90dfa9f33a17af98dac8325620f5bf50eb2e80f0

**Review by Jonoym — APPROVED** [review]
Checked everything out and it looks good to me.

**Review by MTbir — APPROVED** [review]

**Pull request merged**
