### PR TITLE
Team 1 <Character Animations, Healthbar updates and Dialogue Triggers>

### PR DESCRIPTION
**Pull request by Jonoym**
Functionality added to the game:
* The main character now has a full set of animations, walking and attacking
* The health bar display size has been changed and a health percentage has been added
* Textboxes when open have a display box around it (will be changed later)
* Trigger Entity in top right corner which opens the text box once the player is close enough.

### CODE REVIEW

**Review by jac0be — COMMENTED** [review]
Hi guys, the gradlew build javadoc failed, you guys have a merge conflict message hanging in KeyboardPlayerInputComponent.java:149. 

Otherwise looks good!

**Comment by Jonoym** [comment]
Was is the "<<<<<<< HEAD" in the javadoc?

**Comment by jac0be** [comment]
> Was is the "<<<<<<< HEAD" in the javadoc?

Yeah that was it

**Review by jac0be — APPROVED** [review]
Looks good to me!

**Review by eco9898 — APPROVED** [review]

**Pull request merged**
