### PR TITLE
Team 1 Cutscene Improvements

### PR DESCRIPTION
**Pull request by Jonoym**
Additional features have been added to the display of the cutscenes.
- The aspect ratio of the screen will change once a cutscene starts, this should be shown by the slow fading in and out of the black bars
- Dialogue between characters will alternate between speakers
- Updated text box and character images
- Tutorial room added on Test Area map with other NPC enemies being removed
- Sequential ordered dialogue on repeat encounters with the prisoner NPC
- Randomised dialogue on encounters with the Loki NPC
- Progression through cutscenes can now be triggered with mouse clicks
- Addition of new dialogue to be displayed
- Dialogue for the ForestGameArea will start the main text sequence while TestArea will start the tutorial text sequence

### CODE REVIEW

**Comment by eco9898** [comment]
I've noticed the cutscenes now create a lot of lag and talking to Loki causes the player to start attacking for a second or two

**Comment by Jonoym** [comment]
The attacking is intentionally and was being used to test if forcing attacks was possible to be utilised in a cutscene, I'll have a look at the lag issues, they will probably be caused by the black bars so I'll see if I can make it less intensive, is there anything specific about the lag? Anything in particular that will visibly lag?

**Review by eco9898 — CHANGES_REQUESTED** [review]
If you can't get the cutscene black bars to work smoothly that's ok, everything else looks fine, but I do recommend removing the forced attacks before pushing to main

**Comment by Jonoym** [comment]
I've tried to reduce the lag on the bar movement, let me know if it's still causing lag. I've also removed the attack animations and will push once I have a completed version with it working. I noticed that you changed the BooleanObject type to a regular boolean. I've change it back to BooleanObject because I need a reference to the object instead of the primitive type being passed in through the function call since it occurs recursively. I need the reference because the value changes outside of the method call.

**Review by eco9898 — COMMENTED** [review]
The game itself doesn't lag anymore, but the text animation is a little bit jumpy still. Also, is the bottom left Loki used to demonstrate you can force the player to kill enemies?

**Review by eco9898 — APPROVED** [review]

**Comment by Jonoym** [comment]
Yea, the kill cutscenes will be very dependent on the map and there's no map at the moment, it's mostly to show how it would be implemented,.

**Review by GreyAtlantean — APPROVED** [review]

**Pull request merged**
