### PR TITLE
Team 5 - Improved Attack

### PR DESCRIPTION
**Pull request by jac0be**
Improved Attack
https://github.com/UQdeco2800/2021-studio-2/issues/115

Inclusion of Improved Axe, as well as 2 new weapons:
Mjolnir & Laevitan (Loki's Spear).

### CODE REVIEW

**Review by martinrbaer — APPROVED** [review]
astounding work, as always

**Comment by eco9898** [comment]
I merged main into this branch, however the player entity is now very small.

**Comment by Jonoym** [comment]
Eli, don't change anything yet

**Comment by jac0be** [comment]
Stop messing with the branch please, was about to push it and now have to solve more conflicts.

**Comment by Jonoym** [comment]
Check out the new pull request, I fixed the conflicts between main and your branch

**Comment by jac0be** [comment]
> Check out the new pull request, I fixed the conflicts between main and your branch

Hi guys, I've fixed everything in this branch, and it all works fine. I'll merge this branch with main.

**Comment by Jonoym** [comment]
It doesn't run, you need to change the arguments. Could you see if everything is working on my pull request? It should have all of the conflicts fixed for your branch as well as other bug fixes.

**Comment by Jonoym** [comment]
ff

**Comment by eco9898** [comment]
Hadn't approved because I was still doing some merge fixes but those have all been pushed separately now that this was pushed before all the conflicts were fixed.

**Comment by jac0be** [comment]
Hi guys, not sure what was happening on your side, but this branch didn't have any conflicts with main when it was merged. If anyone wants to make changes to seperate branches in the future please let the branch team leader know what the situation is beforehand, otherwise the team doesn't know what changes are needed/what's happening on the branch.

**Pull request merged**
