### PR TITLE
Team 5 <Character attack>

### PR DESCRIPTION
**Pull request by jac0be**
This contains all features listed in #3 
Plus main music theme! #55

### CODE REVIEW

**Review by Jonoym — APPROVED** [review]
Checked all the functionality out and it looks good. Might want to remove the print statements to console before completing the merge.

**Review by martinrbaer — APPROVED** [review]
This all works as intended

**Review by sadrabt — APPROVED** [review]
Features added are working well

**Comment by martinrbaer** [comment]
Whole of team-5 approves

**Pull request merged**
