### PR TITLE
Team 2

### PR DESCRIPTION
**Pull request by eco9898**
Still awaiting some bug fixes should be ready around mid day 14/9

### CODE REVIEW

**Comment by eco9898** [comment]
There are still some major and minor bugs but they will need to be left to the next sprint

**Comment by eco9898** [comment]
closes #96

**Comment by jackemerson** [comment]
Course staff do not review pull requests. This is for your team and/or other studio members to review.

**Comment by eco9898** [comment]
@jackemerson sorry, there is nothing that said you were a course staff when choosing people to review.

**Comment by joshuaobrien** [comment]
Happy to review this, but it looks like maybe you need to rebase first?

**Comment by eco9898** [comment]
Did you have to remove everyone though, some of those I know were students

**Comment by Jonoym** [comment]
When Team 4 merges, there might be a lot of merge conflicts that you guys will need to fix.

**Comment by eco9898** [comment]
> maybe you need to rebase first

We haven't been rebasing in this studio. This would cause issues with other pull requests.

**Comment by jackemerson** [comment]
> @jackemerson sorry, there is nothing that said you were a course staff when choosing people to review.

Nor, perhaps, anything to suggest I was a studio member.


> Did you have to remove everyone though, some of those I know were students

Consider that you didn't take the time to check whether those you were adding were students; similarly, I don't have the time to review who is in your studio from that list. As you seem to have chosen people at random, I would think it appropriate to clear the list in totality.

Requesting a review isn't about assigning names and expecting someone to review your work. You should reach out to people you wish to have request it. Best not to argue this point.

**Comment by eco9898** [comment]
> When Team 4 merges, there might be a lot of merge conflicts that you guys will need to fix.

The team 4 branch is broken, are they going to merge 4.2 into 4 then main. or just 4.2 into main?

**Comment by eco9898** [comment]
There are no merge conflicts in github... unless you're referring to us implementing the same features or conflicting features

**Comment by Jonoym** [comment]
I think they're merging branch 4.2 into main, there might be merge conflicts after the merge since the main branch has not been updated yet.

**Comment by Jonoym** [comment]
You need to make the changes again.

Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by eco9898** [comment]
Current bug, team 3 blood splatter turns trees red

**Comment by eco9898** [comment]
> You need to make the changes again.
> 
> Error: Could not create the Java Virtual Machine.
> Error: A fatal exception has occurred. Program will exit.

Yeah sorry, I hadn't removed team 4's references to the old ghost entities yet. I was still working on the merge conflict

**Comment by eco9898** [comment]
Oh, wait, you mean that thing where some pc's don't support the way gradle builds the game?

**Comment by eco9898** [comment]
Just switch the comment on these lines in guild.gradle:
//jvmArgs = ["-Djava.util.logging.config.file=../../logging.properties"]
 jvmArgs = ["-Djava.util.logging.config.file=../../logging.properties", "-XstartOnFirstThread"]

**Pull request merged**
