### PR TITLE
Team 4 2

### PR DESCRIPTION
**Pull request by GoldMan93**
new pull

### CODE REVIEW

**Comment by Jonoym** [comment]
There are merge conflicts.

**Comment by GoldMan93** [comment]
yes, we are working on it. There is a function in the currently main branch that is broken the code

**Review by Nicolas-Armstrong — APPROVED** [review]

**Comment by GoldMan93** [comment]
All bug fixed. Ready for pull

**Review by othiem — APPROVED** [review]

**Review by BenjaminGonzalez — APPROVED** [review]
All good

**Review by parker334 — APPROVED** [review]

**Review by GreyAtlantean — APPROVED** [review]

**Pull request merged**
