### PR TITLE
Team 2

### PR DESCRIPTION
**Pull request by eco9898**
All are features from #5

### CODE REVIEW

**Comment by eco9898** [comment]
closes #5

**Comment by Jonoym** [comment]
Having trouble running the game through gradle, the game works if run with IntelliJ but here is the message when running it with ./gradlew clean build run

Unrecognized option: -XstartOnFirstThread
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Review by jac0be — COMMENTED** [review]
Also having the same issues building it through gradle.

**Comment by eco9898** [comment]
That argument was meant to be removed but when merging in main it may have come back. It causes issues on some windows machines.

**Comment by eco9898** [comment]
> Also, it may help with clarity if the arrows did not make a collision sound if not colliding with another entity.

The sound is meant to be it breaking. In this case it breaks when it hits the ground.

**Comment by eco9898** [comment]
Following up, the recent commits appear to have stopped my computer from building the project too

**Comment by eco9898** [comment]
The test service can build the project, so it is a client issue. However, it is still an issue that didn't exist previously

**Comment by eco9898** [comment]
I found the issue. I had deleted idea.template, which is needed for intellij to setup the project when loaded for the first time. I have also removed the extra argument that was meant to be removed last week.

**Comment by eco9898** [comment]
@jac0be @Jonoym If you can build the latest version, please feel free to merge when ready. Otherwise I will have to look into it a bit more. I did a clean install on my laptop and desktop and everything worked well.

**Comment by Jonoym** [comment]
I think everything looks fine at the moment. There have been some merges with main since the request e.g. player attacks with space bar will print debugging info in the console here but not on main.

**Pull request merged**
